#!/usr/bin/env python3

import subprocess as sp
import re

# Use the exact tag if there is one
try:
    my_tag = sp.check_output(["git", "describe", "--tags", "--exact-match", "--match", "v*"], stderr=sp.DEVNULL).decode("utf-8").strip()
    print(my_tag[1:])
    exit(0)
except sp.CalledProcessError:
    pass

new_tag = None

# Use "major.minor.<patch+1>" and push a new tag if there is a prior version tag but not a current one
try:
    raw_tag = sp.check_output(["git", "describe", "--tags", "--match", "v*"], stderr=sp.DEVNULL).decode("utf-8").strip()
    tag_parts = re.match(r"^v(\d+\.\d+)\.(\d+)-(\d+)-([a-z0-9]+)$", raw_tag)
    if tag_parts is not None:
        next_patch = int(tag_parts.group(2)) + 1
        new_tag = f"v{tag_parts.group(1)}.{next_patch}"
except sp.CalledProcessError:
    pass

# Use "0.0.1" if there is no prior version tag
new_tag = new_tag or "v0.0.1"

sp.check_call(["git", "tag", new_tag], stderr=sp.DEVNULL)

print(new_tag[1:])
